# Generated by Django 3.1.7 on 2021-03-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
